-- ============================================================================
-- 02_RAW_TABLES.SQL - Domain-specific typed table schemas
-- ============================================================================
USE DATABASE AUTOMOTIVE_SUPPLIER_QUALITY;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW.PLANTS (
  PLANT_ID VARCHAR(20) NOT NULL, PLANT_NAME VARCHAR(200), PROVINCE VARCHAR(50), PLANT_TYPE VARCHAR(30), CAPACITY FLOAT, UNIT VARCHAR(20), STATUS VARCHAR(20), COMMISSIONED_DATE DATE, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.PRODUCTION_RUNS (
  RUN_ID VARCHAR(30) NOT NULL, ENTITY_ID VARCHAR(20), RUN_DATE DATE, OUTPUT_QTY FLOAT, UNIT VARCHAR(20), RUNTIME_HOURS FLOAT, DOWNTIME_HOURS FLOAT, EFFICIENCY_PCT FLOAT, COST FLOAT, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.QUALITY_CHECKS (
  RECORD_ID VARCHAR(30) NOT NULL, ENTITY_ID VARCHAR(20), RECORD_DATE TIMESTAMP, VALUE FLOAT, CATEGORY VARCHAR(50), STATUS VARCHAR(20), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.SUPPLIERS (
  SUPPLIER_ID VARCHAR(20) NOT NULL, SUPPLIER_NAME VARCHAR(200), COUNTRY VARCHAR(50), CATEGORY VARCHAR(50), TIER INT, QUALITY_SCORE FLOAT, DELIVERY_SCORE FLOAT, STATUS VARCHAR(20), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
