-- Generated from generator/demo_specs/aws-thailand-automotive-supplier-quality.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-thailand-automotive-supplier-quality
-- This is the schema that is actually deployed for THAILAND_AUTOMOTIVE_SUPPLIER_QUALITY.

-- Alerts fire on the bottom tail of Supplier PPM (Avg)
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_SUPPLIER_PPM_AVG) AS T
  FROM RAW.INCOMING_INSPECTION
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_SUPPLIER_PPM_AVG <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_SUPPLIER_PPM_AVG), 2) AS AVG_SUPPLIER_PPM,
  ROUND(AVG(f.KPI_ON_TIME_DELIVERY), 2) AS AVG_ON_TIME_DELIVERY,
  ROUND(AVG(f.KPI_AT_RISK_SUPPLIERS), 2) AS AVG_AT_RISK_SUPPLIERS,
  ROUND(AVG(f.KPI_DUAL_SOURCE_COVERAGE), 2) AS AVG_DUAL_SOURCE_COVERAGE,
  ROUND(AVG(f.KPI_AVG_LEAD_TIME), 2) AS AVG_LEAD_TIME
FROM RAW.INCOMING_INSPECTION f
JOIN RAW.THAI_AUTO_INDUSTRY e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_SUPPLIER_PPM_AVG), 2) AS AVG_SUPPLIER_PPM,
  ROUND(AVG(f.KPI_ON_TIME_DELIVERY), 2) AS AVG_ON_TIME_DELIVERY,
  ROUND(AVG(f.KPI_AT_RISK_SUPPLIERS), 2) AS AVG_AT_RISK_SUPPLIERS,
  ROUND(AVG(f.KPI_DUAL_SOURCE_COVERAGE), 2) AS AVG_DUAL_SOURCE_COVERAGE,
  ROUND(AVG(f.KPI_AVG_LEAD_TIME), 2) AS AVG_LEAD_TIME
FROM RAW.INCOMING_INSPECTION f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_SUPPLIER_PPM_AVG) AS KPI_SUPPLIER_PPM_AVG, AVG(KPI_ON_TIME_DELIVERY) AS KPI_ON_TIME_DELIVERY, AVG(KPI_AT_RISK_SUPPLIERS) AS KPI_AT_RISK_SUPPLIERS, AVG(KPI_DUAL_SOURCE_COVERAGE) AS KPI_DUAL_SOURCE_COVERAGE, AVG(KPI_AVG_LEAD_TIME) AS KPI_AVG_LEAD_TIME FROM RAW.INCOMING_INSPECTION),
     en AS (SELECT SUM(KPI_CRITICAL_NCRS_OPEN) AS KPI_CRITICAL_NCRS_OPEN, SUM(KPI_ACTIVE_SUPPLIERS) AS KPI_ACTIVE_SUPPLIERS FROM RAW.THAI_AUTO_INDUSTRY)
  SELECT 1 AS SORT_ORDER, 'Supplier PPM (Avg)' AS TITLE, KPI_SUPPLIER_PPM_AVG AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_SUPPLIER_PPM_AVG)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Critical NCRs Open' AS TITLE, KPI_CRITICAL_NCRS_OPEN AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_CRITICAL_NCRS_OPEN)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'On-Time Delivery' AS TITLE, KPI_ON_TIME_DELIVERY AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_ON_TIME_DELIVERY), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Active Suppliers' AS TITLE, KPI_ACTIVE_SUPPLIERS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_ACTIVE_SUPPLIERS)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'At-Risk Suppliers' AS TITLE, KPI_AT_RISK_SUPPLIERS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_AT_RISK_SUPPLIERS)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Dual-Source Coverage' AS TITLE, KPI_DUAL_SOURCE_COVERAGE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_DUAL_SOURCE_COVERAGE)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Avg Lead Time' AS TITLE, KPI_AVG_LEAD_TIME AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_AVG_LEAD_TIME)) AS DECIMAL(38,0))) || ' ' || 'days' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
