-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Supplier Quality Management
-- ============================================================================
USE DATABASE SUPPLIER_QUALITY;
USE SCHEMA ML;

-- ML.FORECAST: NCR_FORECAST_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.NCR_FORECAST_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.NCR_TRENDS'),
  SERIES_COLNAME => 'SUPPLIER_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y'
  
);

CREATE OR REPLACE TABLE ML.NCR_FORECAST_MODEL_RESULTS AS
SELECT * FROM TABLE(ML.NCR_FORECAST_MODEL!FORECAST(FORECASTING_PERIODS => 14));

-- ML.ANOMALY_DETECTION: SUPPLIER_ANOMALY_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.SUPPLIER_ANOMALY_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.SUPPLIER_RISK_SCORES'),
  SERIES_COLNAME => 'SUPPLIER_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE ML.SUPPLIER_ANOMALY_MODEL_RESULTS AS
SELECT * FROM TABLE(ML.SUPPLIER_ANOMALY_MODEL!DETECT_ANOMALIES(INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.SUPPLIER_RISK_SCORES'), SERIES_COLNAME => 'SUPPLIER_ID', TIMESTAMP_COLNAME => 'DS', TARGET_COLNAME => 'Y'));

