-- ============================================================================
-- 99_RESET.SQL — Reset Supplier Quality Management to clean demo state
-- ============================================================================
USE DATABASE SUPPLIER_QUALITY;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_PARSE_NEW_AUDITS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_REFRESH_RISK_SCORES SUSPEND;
ALTER TASK IF EXISTS APP.TASK_EXPORT_ICEBERG SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.SUPPLIER_RISK_SCORES REFRESH;
ALTER DYNAMIC TABLE CURATED.NCR_TRENDS REFRESH;
ALTER DYNAMIC TABLE CURATED.AUDIT_COMPLIANCE REFRESH;
ALTER DYNAMIC TABLE CURATED.COPQ_SUMMARY REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM SUPPLIER_QUALITY.RAW.AUDIT_REPORTS → 450
-- SELECT COUNT(*) FROM SUPPLIER_QUALITY.RAW.NON_CONFORMANCES → 3200
-- SELECT COUNT(*) FROM SUPPLIER_QUALITY.CURATED.SUPPLIER_RISK_SCORES WHERE RISK_SCORE > 80 → 14

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_EXPORT_ICEBERG RESUME;
ALTER TASK IF EXISTS APP.TASK_REFRESH_RISK_SCORES RESUME;
ALTER TASK IF EXISTS APP.TASK_PARSE_NEW_AUDITS RESUME;
